pluginManagement {
    repositories {
        maven {
            url = 'https://jitpack.io'
            content {
                includeGroup 'com.github.zhongbai2333.BenchMod'
            }
        }
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'com.zhongbai233.minecraft-bench') {
                useModule("com.github.zhongbai2333.BenchMod:bench-gradle-plugin:${requested.version}")
            }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'YuushyaModellingEnhancedEditor'
